name: 'Changeset Autopilot'
description: 'Automate changeset-based releases with branch-specific configurations'
author: 'Pixpilot'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: package
  color: blue

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: GitHub token for authentication
    required: true
  NPM_TOKEN:
    description: NPM token for publishing
    required: true
  BOT_NAME:
    description: Optional bot name
    required: false
    default: 'changesets-autopilot'
  BRANCHES:
    description: Branch configuration for releases (YAML array)
    required: false
    default: |
      - main
      - name: next
        prerelease: rc
        channel: next
  CREATE_RELEASE:
    description: Enable or disable GitHub release creation
    required: false
    default: 'true'
  PUSH_TAGS:
    description: Enable or disable pushing tags to GitHub
    required: false
    default: 'true'
  AUTO_CHANGESET:
    description: Enable or disable automatic changeset generation and versioning
    required: false
    default: 'true'
  GROUP_RELEASES:
    description: Enable grouping of releases by package names instead of individual releases
    required: false
    default: 'false'
  GROUP_BY:
    description: How to group packages for releases (prefix, directory)
    required: false
    default: 'prefix'

# Define your outputs here.
outputs:
  published:
    description: Whether packages were published

runs:
  using: node20
  main: dist/index.js
