/**
 * Checks if a commit message indicates a version or release commit generated by this action
 */
export function isVersionOrReleaseCommit(message: string): boolean {
  const trimmedMessage = message.trim();

  // Single package release: "chore(release): 1.2.3 [skip ci]"
  if (
    /^chore\(release\):\s+\d+\.\d+\.\d+(-\w+(\.\d+)?)?\s+\[skip ci\]$/i.test(
      trimmedMessage,
    )
  ) {
    return true;
  }

  // Multi-package release: "chore(release): bump package versions [skip ci]"
  if (trimmedMessage === 'chore(release): bump package versions [skip ci]') {
    return true;
  }

  // Legacy pattern (for backward compatibility): "chore(release): version packages [skip ci]"
  if (trimmedMessage === 'chore(release): version packages [skip ci]') {
    return true;
  }

  return false;
}
