/**
 * Checks if a commit message indicates a version or release commit generated by this action
 */
export function isVersionOrReleaseCommit(message: string): boolean {
  const trimmedMessage = message.trim();
  if (!/^chore\(release\): +/iu.test(trimmedMessage)) {
    return false;
  }

  const releaseBody = trimmedMessage.replace(/^chore\(release\): +/iu, '');
  const normalizedReleaseBody = releaseBody.toLowerCase();

  if (normalizedReleaseBody === 'bump package versions [skip ci]') {
    return true;
  }
  if (normalizedReleaseBody === 'version packages [skip ci]') {
    return true;
  }

  const marker = '[skip ci]';
  if (!normalizedReleaseBody.endsWith(marker)) {
    return false;
  }

  if (
    normalizedReleaseBody.indexOf(marker) !==
    normalizedReleaseBody.length - marker.length
  ) {
    return false;
  }

  const packageAndVersion = releaseBody.slice(0, -marker.length).trim();
  if (packageAndVersion.length === 0) {
    return false;
  }

  if (/\s/u.test(packageAndVersion)) {
    return false;
  }

  const versionSeparatorIndex = packageAndVersion.lastIndexOf('@');
  const hasPackage = versionSeparatorIndex > 0;
  const version = hasPackage
    ? packageAndVersion.slice(versionSeparatorIndex + 1)
    : packageAndVersion;

  if (hasPackage) {
    const packageName = packageAndVersion.slice(0, versionSeparatorIndex);
    const isScopedPackage = packageName.startsWith('@');
    const packageNamePattern = isScopedPackage ? /^@[-\w.]+\/[-\w.]+$/u : /^[-\w.]+$/u;
    if (!packageNamePattern.test(packageName)) {
      return false;
    }
  }

  return /^\d+\.\d+\.\d+(?:-[\w.-]+)?$/u.test(version);
}
