import fs from 'fs';

import * as core from '@actions/core';
import { beforeEach, describe, expect, test, vi } from 'vitest';

import { cleanupAutoGeneratedChangesetFiles } from '../../src/changeset/cleanup-changeset-files';

vi.mock('@actions/core');
vi.mock('fs');

describe('cleanupAutoGeneratedChangesetFiles', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test('cleans up auto-generated changeset files', () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readdirSync).mockReturnValue([
      'auto-generated-at-1234567890.md',
      'auto-generated-at-0987654321.md',
      'manual-changeset.md',
      'README.md',
    ] as any);
    vi.mocked(fs.unlinkSync).mockImplementation(() => {});

    cleanupAutoGeneratedChangesetFiles();

    expect(fs.unlinkSync).toHaveBeenCalledTimes(2);
    expect(fs.unlinkSync).toHaveBeenCalledWith(
      expect.stringContaining('auto-generated-at-1234567890.md'),
    );
    expect(fs.unlinkSync).toHaveBeenCalledWith(
      expect.stringContaining('auto-generated-at-0987654321.md'),
    );
    expect(core.info).toHaveBeenCalledWith(
      'Cleaning up 2 auto-generated changeset files',
    );
    expect(core.info).toHaveBeenCalledWith('Removed: auto-generated-at-1234567890.md');
    expect(core.info).toHaveBeenCalledWith('Removed: auto-generated-at-0987654321.md');
  });

  test('handles missing changeset directory', () => {
    vi.mocked(fs.existsSync).mockReturnValue(false);

    cleanupAutoGeneratedChangesetFiles();

    expect(fs.readdirSync).not.toHaveBeenCalled();
    expect(fs.unlinkSync).not.toHaveBeenCalled();
  });

  test('handles no auto-generated files', () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readdirSync).mockReturnValue([
      'manual-changeset.md',
      'README.md',
    ] as any);

    cleanupAutoGeneratedChangesetFiles();

    expect(fs.unlinkSync).not.toHaveBeenCalled();
    expect(core.info).toHaveBeenCalledWith(
      'No auto-generated changeset files to clean up',
    );
  });

  test('handles file deletion errors gracefully', () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readdirSync).mockReturnValue(['auto-generated-at-1234567890.md'] as any);
    vi.mocked(fs.unlinkSync).mockImplementation(() => {
      throw new Error('Permission denied');
    });

    cleanupAutoGeneratedChangesetFiles();

    expect(core.warning).toHaveBeenCalledWith(
      'Failed to remove auto-generated-at-1234567890.md: Error: Permission denied',
    );
  });
});
