import * as core from '@actions/core';

import {
  configurePrereleaseMode,
  ensureChangesets,
  cleanupAutoGeneratedChangesetFiles,
} from './changeset';
import { ensureChangesetsAvailable } from './changeset/ensure-changesets-available';
import { runChangesetVersion } from './changeset/run-changeset-version';
import { getActionInputs, getBranchConfig, validateBranchConfiguration } from './config';
import { configureGit, commitAndPush } from './git';
import { createReleasesForPackages } from './github/create-releases-for-packages';
import { pushChangesetTags } from './github/push-changeset-tags';
import { publishPackages } from './publisher';

/**
 * The main function for the action.
 */
export async function run(): Promise<void> {
  try {
    // Ensure changesets is available
    ensureChangesetsAvailable();

    // Initialize inputs and configuration
    const {
      githubToken,
      npmToken,
      botName,
      branches,
      createRelease: shouldCreateRelease,
      pushTags,
    } = getActionInputs();
    const branchConfig = getBranchConfig(branches);

    // Validate branch configuration
    if (!validateBranchConfiguration(branchConfig)) {
      return;
    }

    // Configure Git user
    const git = await configureGit(botName);

    // Ensure we have changesets to work with
    const hasChangesetFiles = await ensureChangesets();
    core.info(`DEBUG: hasChangesetFiles after ensureChangesets: ${hasChangesetFiles}`);

    // Manage pre-release mode based on branch configuration
    configurePrereleaseMode(branchConfig);

    // Version and push changes if we have changesets
    if (hasChangesetFiles) {
      core.info('Processing versioning and git operations...');

      runChangesetVersion(githubToken);

      await commitAndPush(git, githubToken);

      // Publish to npm if token is provided
      if (npmToken) {
        const releasedPackages = await publishPackages(branchConfig, npmToken);
        core.info('Packages published successfully!');

        // Clean up auto-generated changeset files in prerelease mode
        if (branchConfig.prerelease) {
          cleanupAutoGeneratedChangesetFiles();
        }

        // NOW push the tags that were created by changeset publish
        const repo = process.env.GITHUB_REPOSITORY;
        if (repo && githubToken && pushTags) {
          try {
            await pushChangesetTags(git, githubToken, repo);
            // Create GitHub releases for published packages
            if (releasedPackages.length > 0 && shouldCreateRelease) {
              await createReleasesForPackages({
                releasedPackages,
                githubToken,
                repo,
              });
            }
          } catch (error) {
            core.warning(`Failed to push tags: ${String(error)}`);
          }
        }
      } else {
        core.info('No npm token provided, skipping publish step.');
      }
    } else {
      core.info('No changesets to process. Action completed.');
    }

    core.info('Changeset autopilot completed successfully!');
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    core.setFailed(`Action failed: ${errorMessage}`);
  }
}
